sonar.projectKey=formularios_dinamicos_mf
sonar.projectName=formularios_dinamicos_mf
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss,**/coverage/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8
